version: '3.8'

services:
    # Frontend
    web:
        image: jitsi/web:stable
        container_name: jitsi-web
        restart: unless-stopped
        ports:
            - '${HTTP_PORT:-80}:80'
            - '${HTTPS_PORT:-443}:443'
        volumes:
            - ${CONFIG}/web:/config:Z
            - ${CONFIG}/web/cert:/etc/letsencrypt:Z
            - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts:Z
        environment:
            - ENABLE_AUDIO_PROCESSING
            - ENABLE_AUTH
            - ENABLE_GUESTS
            - ENABLE_LETSENCRYPT
            - ENABLE_HTTP_REDIRECT
            - ENABLE_HSTS
            - ENABLE_XMPP_WEBSOCKET
            - DISABLE_HTTPS
            - LETSENCRYPT_DOMAIN
            - LETSENCRYPT_EMAIL
            - PUBLIC_URL
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_BOSH_URL_BASE
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - XMPP_RECORDER_DOMAIN
            - ETHERPAD_URL_BASE
            - TZ
            - AMPLITUDE_ID
            - ANALYTICS_SCRIPT_URLS
            - ANALYTICS_WHITELISTED_EVENTS
            - BRIDGE_CHANNEL
            - BRANDING_DATA_URL
            - CALLSTATS_CUSTOM_SCRIPT_URL
            - CALLSTATS_ID
            - CALLSTATS_SECRET
            - CHROME_EXTENSION_BANNER_JSON
            - CONFCODE_URL
            - CONFIG_EXTERNAL_CONNECT
            - DEFAULT_LANGUAGE
            - DEPLOYMENTINFO_ENVIRONMENT
            - DEPLOYMENTINFO_ENVIRONMENT_TYPE
            - DEPLOYMENTINFO_REGION
            - DEPLOYMENTINFO_SHARD
            - DEPLOYMENTINFO_USERREGION
            - DIALIN_NUMBERS_URL
            - DIALOUT_AUTH_URL
            - DIALOUT_CODES_URL
            - DROPBOX_APPKEY
            - DROPBOX_REDIRECT_URL
            - ENABLE_CLOSEPAGE
            - ENABLE_PREJOINPAGE
            - ENABLE_WELCOME_PAGE
            - ENABLE_CLOSE_PAGE
            - ENABLE_RECORDING
            - ENABLE_REMB
            - ENABLE_REQUIRE_DISPLAY_NAME
            - ENABLE_SIMULCAST
            - ENABLE_STATS_ID
            - ENABLE_STEREO
            - ENABLE_SUBDOMAINS
            - ENABLE_TALK_WHILE_MUTED
            - ENABLE_TCC
            - ENABLE_TRANSCRIPTIONS
            - JICOFO_AUTH_USER
            - HIDE_PREMEETING_BUTTONS
            - INTERFACECONFIG_FILMSTRIP_ENABLED
            - INTERFACECONFIG_GENERATE_ROOMNAMES_ON_WELCOME_PAGE
            - INTERFACECONFIG_HIDE_INVITE_MORE_HEADER
            - INTERFACECONFIG_MOBILE_APP_PROMO
            - INTERFACECONFIG_PROVIDER_NAME
            - INTERFACECONFIG_RANDOM_AVATAR_URL_PREFIX
            - INTERFACECONFIG_RANDOM_AVATAR_URL_SUFFIX
            - INTERFACECONFIG_SETTINGS_SECTIONS
            - INTERFACECONFIG_SHOW_JITSI_WATERMARK
            - INTERFACECONFIG_SHOW_WATERMARK_FOR_GUESTS
            - INTERFACECONFIG_UNSUPPORTED_BROWSER_URL
            - INTERFACECONFIG_VIDEO_LAYOUT_FIT
            - INVITE_SERVICE_URL
            - PEOPLE_SEARCH_URL
            - RESOLUTION
            - RESOLUTION_MIN
            - RESOLUTION_WIDTH
            - RESOLUTION_HEIGHT
            - START_BITRATE
            - TESTING_CAP_SCREENSHARE_BITRATE
            - TESTING_OCTO_PROBABILITY
            - TOKEN_AUTH_URL
            - TOOLBAR_BUTTONS
            - WELCOME_FOOTER_ADDITIONAL_CONTENT
            - WELCOME_FOOTER_LINKS
            - WELCOME_PAGE_ADDITIONAL_CONTENT
            - WELCOME_PAGE_ADDITIONAL_TOOLBAR_CONTENT
            - WELCOME_PAGE_TITLE
        networks:
            - meet.jitsi
        depends_on:
            - prosody

    # XMPP server
    prosody:
        image: jitsi/prosody:stable
        container_name: jitsi-prosody
        restart: unless-stopped
        expose:
            - '5222'
            - '5347'
            - '5280'
        volumes:
            - ${CONFIG}/prosody/config:/config:Z
            - ${CONFIG}/prosody/prosody-plugins-custom:/prosody-plugins-custom:Z
        environment:
            - AUTH_TYPE
            - ENABLE_AUTH
            - ENABLE_GUESTS
            - ENABLE_LOBBY
            - ENABLE_XMPP_WEBSOCKET
            - GLOBAL_MODULES
            - GLOBAL_CONFIG
            - LDAP_URL
            - LDAP_BASE
            - LDAP_BINDDN
            - LDAP_BINDPW
            - LDAP_FILTER
            - LDAP_AUTH_METHOD
            - LDAP_VERSION
            - LDAP_USE_TLS
            - LDAP_TLS_CIPHERS
            - LDAP_TLS_CHECK_PEER
            - LDAP_TLS_CACERT_FILE
            - LDAP_TLS_CACERT_DIR
            - LDAP_START_TLS
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_MODULES
            - XMPP_MUC_MODULES
            - XMPP_INTERNAL_MUC_MODULES
            - XMPP_RECORDER_DOMAIN
            - XMPP_CROSS_DOMAIN
            - JICOFO_COMPONENT_SECRET
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - JVB_AUTH_USER
            - JVB_AUTH_PASSWORD
            - JIGASI_XMPP_USER
            - JIGASI_XMPP_PASSWORD
            - JIBRI_RECORDER_USER
            - JIBRI_RECORDER_PASSWORD
            - JIBRI_XMPP_USER
            - JIBRI_XMPP_PASSWORD
            - ENABLE_RECORDING
            - TZ
        networks:
            - meet.jitsi

    # Focus component
    jicofo:
        image: jitsi/jicofo:stable
        container_name: jitsi-jicofo
        restart: unless-stopped
        volumes:
            - ${CONFIG}/jicofo:/config:Z
        environment:
            - AUTH_TYPE
            - BRIDGE_AVG_PARTICIPANT_STRESS
            - BRIDGE_STRESS_THRESHOLD
            - ENABLE_AUTH
            - ENABLE_AUTO_OWNER
            - ENABLE_CODEC_VP8
            - ENABLE_CODEC_VP9
            - ENABLE_CODEC_H264
            - ENABLE_OCTO
            - ENABLE_RECORDING
            - ENABLE_SCTP
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - JICOFO_ENABLE_BRIDGE_HEALTH_CHECKS
            - JICOFO_CONF_INITIAL_PARTICIPANT_WAIT_TIMEOUT
            - JICOFO_CONF_SINGLE_PARTICIPANT_TIMEOUT
            - JICOFO_ENABLE_HEALTH_CHECKS
            - JICOFO_SHORT_ID
            - JICOFO_RESERVATION_ENABLED
            - JICOFO_RESERVATION_REST_BASE_URL
            - JIBRI_BREWERY_MUC
            - JIBRI_REQUEST_RETRIES
            - JIBRI_PENDING_TIMEOUT
            - JIGASI_BREWERY_MUC
            - JIGASI_SIP_URI
            - JVB_BREWERY_MUC
            - MAX_BRIDGE_PARTICIPANTS
            - OCTO_BRIDGE_SELECTION_STRATEGY
            - SENTRY_DSN="${JICOFO_SENTRY_DSN:-0}"
            - SENTRY_ENVIRONMENT
            - SENTRY_RELEASE
            - TZ
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_MUC_DOMAIN
            - XMPP_RECORDER_DOMAIN
            - XMPP_SERVER
        depends_on:
            - prosody
        networks:
            - meet.jitsi

    # Video bridge
    jvb:
        image: jitsi/jvb:stable
        container_name: jitsi-jvb
        restart: unless-stopped
        ports:
            - '${JVB_PORT:-10000}:${JVB_PORT:-10000}/udp'
            - '${JVB_TCP_PORT:-4443}:${JVB_TCP_PORT:-4443}'
        volumes:
            - ${CONFIG}/jvb:/config:Z
        environment:
            - DOCKER_HOST_ADDRESS
            - ENABLE_COLIBRI_WEBSOCKET
            - ENABLE_OCTO
            - JVB_AUTH_USER
            - JVB_AUTH_PASSWORD
            - JVB_BREWERY_MUC
            - JVB_PORT
            - JVB_TCP_HARVESTER_DISABLED
            - JVB_TCP_PORT
            - JVB_TCP_MAPPED_PORT
            - JVB_STUN_SERVERS
            - JVB_ENABLE_APIS
            - JVB_WS_DOMAIN
            - JVB_WS_SERVER_ID
            - PUBLIC_URL
            - SENTRY_DSN="${JVB_SENTRY_DSN:-0}"
            - SENTRY_ENVIRONMENT
            - SENTRY_RELEASE
            - COLIBRI_REST_ENABLED
            - SHUTDOWN_REST_ENABLED
            - TZ
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_SERVER
        depends_on:
            - prosody
        networks:
            - meet.jitsi    # Apache reverse proxy
    apache:
        image: httpd:2.4-alpine
        container_name: jitsi-apache
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
            - ./apache/conf.d:/usr/local/apache2/conf/conf.d:ro
            - ./ssl:/etc/ssl/certs:ro
            - ./logs/apache:/usr/local/apache2/logs
        depends_on:
            - web
        networks:
            - meet.jitsi

    # Certbot for SSL certificates
    certbot:
        image: certbot/certbot
        container_name: jitsi-certbot
        volumes:
            - ./ssl:/etc/letsencrypt
            - ./ssl-challenge:/var/www/certbot        command: certonly --webroot --webroot-path=/var/www/certbot --email ${LETSENCRYPT_EMAIL} --agree-tos --no-eff-email --staging -d ${LETSENCRYPT_DOMAIN}
        depends_on:
            - apache
        networks:
            - meet.jitsi

    # Watchtower for automatic updates
    watchtower:
        image: containrrr/watchtower
        container_name: jitsi-watchtower
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_SCHEDULE=0 0 4 * * *
        networks:
            - meet.jitsi

networks:
    meet.jitsi:
        driver: bridge
